### ISSUE TITLE
好像没法复制公式到知乎

### ISSUE THREAD

**Issue by varyshare** [mdnice/markdown-nice#106]
**新特性描述：**

**Comment by views63** [comment]
关于知乎的问题，[公式编写注意点](https://docs.mdnice.com/#/%E5%85%AC%E5%BC%8F%E7%BC%96%E5%86%99%E6%B3%A8%E6%84%8F%E7%82%B9?id=%e5%85%ac%e5%bc%8f%e7%bc%96%e5%86%99%e6%b3%a8%e6%84%8f%e7%82%b9) 里面说明了。

知乎的编辑器比较特别，需要单独处理，目前的开发重点是管理模块，这个要排后面一些。

**Comment by guanpengchn** [comment]
已解决
