### ISSUE TITLE
建议添加是否【同步滚动】的按钮

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [mdnice/markdown-nice#112]
**新特性描述：**
建议加个像简书一样选择是否【同步滚动】的按钮

![](https://user-images.githubusercontent.com/26433572/68637681-57f2e680-053a-11ea-8c36-a4f8b9c27657.png)

![](https://user-images.githubusercontent.com/26433572/68637744-8b357580-053a-11ea-810c-8cb9a96afefb.png)

**原因：**
同步滚动**不能**保证「原生」与「预览」的内容是在同一可见区域的

感谢作者提供这么好用的工具，希望能加下这个功能！

**Comment by guanpengchn** [comment]
需要讨论下如何处理

**Comment by AttackXiaoJinJin** [comment]
![](https://user-images.githubusercontent.com/26433572/68832791-d68f8580-06ec-11ea-8c5d-65ed96f827ee.png)

![](https://user-images.githubusercontent.com/26433572/68833101-9c72b380-06ed-11ea-8941-a1fd488a9af3.png)

现在的页面默认就是「原生」与「预览」两个区域是同步滚动的
再次点击【同步按钮】后，「原生」与「预览」各自区域的滚动不影响对方：

![](https://user-images.githubusercontent.com/26433572/68833125-ac8a9300-06ed-11ea-996f-c4de71ce4e96.png)

![](https://user-images.githubusercontent.com/26433572/68832994-4d2c8300-06ed-11ea-9204-13387337bf7c.png)

**Comment by guanpengchn** [comment]
@AttackXiaoJinJin 已经添加
