### ISSUE TITLE
复制粘贴失败

### ISSUE THREAD

**Issue by Smilefisher945** [mdnice/markdown-nice#113]
**运行环境：**

|操作系统|浏览器|
|---|---|
|win|Chrome、firefox|

**错误详情：**
使用chorme浏览器和Firefox浏览器均无法成功复制，点击复制按钮后提示复制成功，但跳转到微信公共平台编辑页面时，粘贴结果为N。

**Comment by acccco** [comment]
提供一下具体的 Chrome / firefox 版本

**Comment by guanpengchn** [comment]
@Smilefisher945 请给出具体的文档，否则很难排查

**Comment by Smilefisher945** [comment]
> 无耻之徒第十季开播了，思绪一下子被拉回7年前，下课后看美剧那种兴奋感、代入感今天仍能回想起来，为了能把这份记忆保存下来打算凭记忆写些东西，虽然文笔不行，但我一定会写，发不发就待定吧。今天先列个目录，也算是推荐吧。

## 1.平民窟里“坑爹”的日常生活
无耻之徒（美版、豆瓣9.0）
## 2.珍爱生命 远离毒品
火线（豆瓣9.5）

毒枭（豆瓣9.3）

绝命毒师（豆瓣9.6）
## 3.下雪天尽量别出门，小心杀手
冰血暴（豆瓣9.0）

八恶人（豆瓣8.4）
## 4.可以伴你成长的喜剧
生活大爆炸

小谢尔顿

摩登家庭

发展受阻

老友记
## 5.重口味
斯巴达克斯

冰与火之歌？
## 6.成人动画
瑞克和莫迪

咱们裸熊
## 7.男士职业发展与时尚指南
广告狂人

风骚律师

大西洋帝国
## 8.女士职业发展
了不起的麦瑟尔夫人
## 9.破案
炸弹客

真探
## 10.科幻
怪奇物语

萤火虫号


...
未完待续

----文档如上----

Chromium 74.0.3729.169
Firefox 70.0.1 (64 位)

**Comment by Smilefisher945** [comment]
点了“重置”按钮，使用默认文字，点击“复制”按钮，粘贴出来结果还是只有一个“N”。

**Comment by Smilefisher945** [comment]
使用360极速浏览器（Chromium 69.0.3497.100）无问题。

**Comment by guanpengchn** [comment]
@Smilefisher945 这个问题第一次见到，我晚上测试下

**Comment by views63** [comment]
未重现。你点复制后直接粘贴到编辑器窗口内容正常吗？

> 
> 
> 点了“重置”按钮，使用默认文字，点击“复制”按钮，粘贴出来结果还是只有一个“N”。

**Comment by Smilefisher945** [comment]
> 
> 
> 未重现。你点复制后直接粘贴到编辑器窗口内容正常吗？
> 
> > 点了“重置”按钮，使用默认文字，点击“复制”按钮，粘贴出来结果还是只有一个“N”。

不正常，粘贴结果为“N”
现在更换为360极速浏览器，就没有问题了。

**Comment by views63** [comment]
> 
> 
> > 未重现。你点复制后直接粘贴到编辑器窗口内容正常吗？
> > > 点了“重置”按钮，使用默认文字，点击“复制”按钮，粘贴出来结果还是只有一个“N”。
> 
> 不正常，粘贴结果为“N”
> 现在更换为360极速浏览器，就没有问题了。

点复制前，f12 打开控制台看看有什么报错吧
![图片](https://user-images.githubusercontent.com/175116/68848332-1e250a00-070b-11ea-8c94-bd84cacb1a8e.png)
