### ISSUE TITLE
微信外链转脚注错误转换标题跳转问题？

### ISSUE THREAD

**Issue by purequant** [mdnice/markdown-nice#114]
**运行环境：**

|操作系统|浏览器|
|---|---|
|~macOS~|Chrome|

**当启用格式化微信外链转脚注时，会将以下形式的标题也转化为脚注：**

例如这个文本：

```md
# anki 神级插件 fastWQ 提取本地朗文音频

- [anki 神级插件 fastWQ 提取本地朗文音频](#anki-神级插件-fastwq-提取本地朗文音频)
  - [前言](#前言)
  - [特制的朗文6本地词典](#特制的朗文6本地词典)
  - [词典配置](#词典配置)
  - [尾声](#尾声)

## 前言

用 anki 学习英语的朋友想必都知道 WordQuery 或者 fastWQ 这种批量制卡必备的工具，并且应该也能够使用在线词典或者本地 mdx 词典进行制卡。

但是使用在线词典，批量制卡速度会比较慢（国外在线词典尤慢）。我此前如果大批量制卡，一般选择有道词典做为音源，但是有道词典发音其实不甚准确。

而一般的本地词典无法精确提取音频、图像、例句这些内容，只能是将整个词典导入，实现如下效果：

![anki神级插件fastWQ提取本地朗文词典内容-2019-8-8-2-58-16.png](https://i.loli.net/2019/08/08/uU7VGIWTfg29a1v.png)

那么，有没有又快又好的制卡方式呢？

## 特制的朗文6本地词典

这个问题想必有很多大神感同身受，早有解决方案。就是通过特制的本地优质词典提取，我们需要的字段。

![anki神级插件fastWQ提取本地朗文词典内容-2019-8-8-3-2-0.png](https://i.loli.net/2019/08/08/Gt87TkAmUYsWnr1.png)

所以，首先得先获取这个特制的朗文6词典。词典地址如下：

> 链接：https://pan.baidu.com/s/1rGIDHHL-VzxsM9fpzhLqqA
> 提取码：9v8u
> 复制这段内容后打开百度网盘手机App，操作更方便哦

## 词典配置

不用担心，配置非常简单，其实插件已经内置了 **本地朗文-LCOCE6** 这一配置项。具体做法为在 anki 菜单栏工具项下调出上图 fastWQ 配置项，点击上图左上角小齿轮，弹出下图：

![anki神级插件fastWQ提取本地朗文词典内容-2019-8-8-3-10-15.png](https://i.loli.net/2019/08/08/KZOs631hSWJwdLT.png)

点击编辑，找出 **DICT_PATH** 项，将其设置为自己本地朗文词典 **L6mp3.mdx** 文件所在目录即可。

![anki神级插件fastWQ提取本地朗文词典内容-2019-8-8-3-11-13.png](https://i.loli.net/2019/08/08/kPF7pqmhfJMEsOy.png)

当然，也可以直接搜索出 LDOCE6.py 文件，然后设置路径即可。
==这边需要注意的是，原文件中词典路径这一项被注释了，需要去调 **#** 注释符。==

## 尾声

完成上面的操作后，重启 anki 即可使设置生效。然后就可以愉快地利用本地朗文进行批量制卡。祝各位朋友制卡愉快。

本文主要参考了[重装WIN10系统及ANKI后，本插件自带的”本地词典-LDOCE6“找不到了？ · Issue #126 · sth2018/FastWordQuery](github_issue "https://github.com/sth2018/FastWordQuery/issues/126")。对 **dly1973** 表示感谢。
```

**错误详情：**

转化时会将标题跳转一起转化成脚注（此是每标题也添加了跳转，而这加微信中是无法实现的），转化效果如下：
![image](https://user-images.githubusercontent.com/26440503/68825978-0b90dd80-06d7-11ea-97f0-7d933e4a8e35.png)
![image](https://user-images.githubusercontent.com/26440503/68825994-19466300-06d7-11ea-9217-b2c09aca6285.png)
希望能修复这个问题，在转化时忽略标题部分。
感谢开发者的辛勤工作。

**Comment by guanpengchn** [comment]
这个是正常现象，因为本来这个对于微信来说就是无效外链

**Comment by purequant** [comment]
嗯，我知道。能不能自动识别标题部分，而不进行转化。毕竟这种标题形式，在很多markdown编辑器中是可以正常跳转的。

**Comment by guanpengchn** [comment]
嗯嗯，对的呀，所以在其他markdown编辑器中就不要格式化就好了呀，格式化就是专门为微信准备的，从逻辑上来说处理这里没有什么问题，其他的markdown编辑器完全没必要格式化转脚注，无论是标题还是正常的外链也都会完好无损的

而且你强调的标题其实本质就是外链，不过是相对路径而已，[a](#前言)如果发布在https://test.com上，那其实就是外链`https://test.com/#前言`，所以这个处理逻辑没有问题的

**Comment by purequant** [comment]
嗯，但是问题就在于如果就这样处理然后复制到微信编辑器上，这样的链接他会显示非法，还得手动删除十分麻烦。所以，希望微信格式化这一步的时候，仅将标题部分的外链处理成标题而不需要添加连接。

**Comment by guanpengchn** [comment]
有截图么，转成脚注不应该非法才对

**Comment by purequant** [comment]
嗯，的确是我说错了，没有显示非法,是我的思想还停留在早期版本上。

**Comment by purequant** [comment]
话说，我今天还真又遇到过非法链接的事了：
![image](https://user-images.githubusercontent.com/26440503/69040252-74a28900-0a28-11ea-80c3-e325dbc28445.png)
像图片中弹出框的链接微信中就是非常法的。

**Comment by guanpengchn** [comment]
@purequant 所以需要转脚注，这个逻辑没问题吧

**Comment by purequant** [comment]
嗯，逻辑是没问题，但是最后效果有问题。这个东西我的本意是标题或者说大纲，但是最后却成了脚注，这部分信息已经在正文中充分展示了，放到脚注没有意义反而影响阅读。

**Comment by guanpengchn** [comment]
@purequant 你可以删掉这部分，改用`[[TOC]]`语法

**Comment by purequant** [comment]
嗯，不过这个toc的语法目前还像还有争议啊，我见有的编辑器认的是`[toc]`

**Comment by guanpengchn** [comment]
这个本来就是markdown语法的补充，叫什么并不通用

**Comment by purequant** [comment]
嗯，希望能最大限度地兼容不同语法。
