### ISSUE TITLE
希望增加GitHub图床上传功能~

### ISSUE THREAD

**Issue by lunawen** [mdnice/markdown-nice#118]
**新特性描述：**
目前已经支持七牛云图床，希望新增GitHub的选项~ 
希望支持把图片存在一个自定义的repo里面，假如可以同步拉取repo的图片就更好了~

**Comment by guanpengchn** [comment]
图床这里，目前的计划是之后会单独启动一个项目，网站上估计不会保留，但是组件上依然会有

**Comment by lunawen** [comment]
好的！谢谢回复～期待新项目

**Comment by guanpengchn** [comment]
已增加
