### ISSUE TITLE
代码高亮组件转换空格丢失

### ISSUE THREAD

**Issue by ElderJames** [mdnice/markdown-nice#122]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows10|Chromium Edge Dev|

**Markdown文本内容：**

```cs
[ServiceContract]
public interface IMyAmazingService {
    ValueTask<SearchResponse> SearchAsync(SearchRequest request);
    // ...
}
```

**错误详情：**

例如：部分代码失去空格
![image](https://user-images.githubusercontent.com/7550366/69529177-b6907980-0faa-11ea-8d6b-2831ac1604f4.png)

**Comment by guanpengchn** [comment]
我这儿没有什么问题，chrome也会这样么

**Comment by ElderJames** [comment]
指定java cs 都会有问题

**Comment by guanpengchn** [comment]
@ElderJames 缓存问题，问题已经找到

**Comment by guanpengchn** [comment]
已经解决，如果看到新的版本弹出对话框则可
