### ISSUE TITLE
希望有vue的版本

### ISSUE THREAD

**Issue by ClawHub** [mdnice/markdown-nice#124]
**新特性描述：vue患者，非常喜欢这个工具，希望出个vue组件**

**Comment by guanpengchn** [comment]
@ClawHub 这个要等等了，暂时不会做这部分工作

**Comment by ClawHub** [comment]
好的，还是很期待的。

**Comment by guanpengchn** [comment]
@ClawHub issue打开吧，之后会完善

**Comment by guanpengchn** [comment]
@ClawHub 今天用户群里发现个vuera，可以试试，有人成功了

**Comment by guanpengchn** [comment]
https://github.com/ElyhG/vuera

**Comment by ClawHub** [comment]
谢谢

**Comment by litandota** [comment]
vuera 可以的，我就是这种方式在用

**Comment by guanpengchn** [comment]
@litandota 有case么，可以分享下不
