### ISSUE TITLE
表格内公式复制粘贴无效

### ISSUE THREAD

**Issue by wylu** [mdnice/markdown-nice#127]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Linux|Chrome|

**Markdown文本内容：**

例如：

```md
| 排序算法 | 平均时间复杂度 | 最好情况 | 最坏情况 | 空间复杂度 | 排序方式 | 稳定性 |
| -------- | -------------- | -------- | -------- | ---------- | -------- | ------ |
| 选择排序 | $O(n^2)$       | $O(n^2)$ | $O(n^2)$ | $O(1)$     | In-place | 不稳定 |
```

**错误详情：**

转换渲染正常：

![DeepinScreenshot_select-area_20191204220514](https://user-images.githubusercontent.com/19390318/70149136-7768d380-16e2-11ea-9256-d17cbabff6c5.png)

复制粘贴后，普通行内公式正常显示，表格内公式没有展示：

![DeepinScreenshot_select-area_20191204220619](https://user-images.githubusercontent.com/19390318/70149305-c878c780-16e2-11ea-8511-5139a766510c.png)

**Comment by guanpengchn** [comment]
表格确实有这种bug，是因为微信的原因，后续会考虑解决方案

**Comment by guanpengchn** [comment]
#103

**Comment by views63** [comment]
也可以考虑用 mathjax 的 array 环境
```tex
$$
\begin{array}{|l|l|}
\hline
排序算法 & 平均时间复杂度 & 最好情况 & 最坏情况 & 空间复杂度 & 排序方式 & 稳定性\\
\hline
选择排序 & O(n^2)       & O(n^2) & O(n^2) & O(1)     & In-place & 不稳定\\
\hline
\end{array}
$$
```

**Comment by guanpengchn** [comment]
目前建议采用 @views63 的方案
