### ISSUE TITLE
微信排版的话公式还是不能很好的支持，图片无法上传

### ISSUE THREAD

**Issue by dazhuangge** [mdnice/markdown-nice#128]
$$
\nabla=\frac{\partial}{\partial x} \boldsymbol{i}+\frac{\partial}{\partial y} \boldsymbol{j}+\frac{\partial}{\partial z} \boldsymbol{k}=\left(\frac{\partial}{\partial x}, \frac{\partial}{\partial y}, \frac{\partial}{\partial z}\right)
$$
这是我的公式，复制到公众平台，提示图片无法上传

可以参考http://md.aclickall.com/ 对公式的处理办法，第一次复制把公式转化为图片并上传到图床，第二次复制就好

不过我看您的预览更好，对于长的公式还可以拖拽

**Comment by guanpengchn** [comment]
@dazhuangge 建议换浏览器再试下，或者加入用户群具体在反馈下问题，我们测试过，使用当前的方法放入30页的数学书都是没有问题的

http://md.aclickall.com/ 转图片的方式并不是最好的处理方法，svg才是更好地方式，已经有很多人成功排版了并且现在在使用

**Comment by dazhuangge** [comment]
我也认为您的方法是好方法而且漂亮，我已经将问题反馈到群里，期待您能看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "灵魂画师牧码"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 下午3:38
收件人: "mdnice/markdown-nice"<markdown-nice@noreply.github.com&gt;; 
抄送: "聪慧的泥人"<805795334@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mdnice/markdown-nice] 微信排版的话公式还是不能很好的支持，图片无法上传 (#128)




@dazhuangge 建议换浏览器再试下，或者加入用户群具体在反馈下问题，我们测试过，使用当前的方法放入30页的数学书都是没有问题的
 
http://md.aclickall.com/ 转图片的方式并不是最好的处理方法，svg才是更好地方式，已经有很多人成功排版了并且现在在使用

**Comment by guanpengchn** [comment]
@dazhuangge 经过验证和公众号有关系，有的公众号就不行，原因未知
