### ISSUE TITLE
希望能将写好的markdown保存在本地文件

### ISSUE THREAD

**Issue by Hu-weitao** [mdnice/markdown-nice#129]
**先夸赞：**
mdnice很好用，尤其在移动设备上，大多数移动设备（例如ipad）上的markdown软件都不能边写边预览，而mdnice做的很好。

**在提个小小要求：**
mdnice和其它markdown软件相比，有个小小的不足：不能将写好的内容直接另存为"本地.md文件"。所以希望大佬能加一个另存为本地文件的功能。感谢！

**Comment by guanpengchn** [comment]
这个得想想加什么位置

**Comment by guanpengchn** [comment]
已经支持
