### ISSUE TITLE
线上的编辑器的的代码块出问题

### ISSUE THREAD

**Issue by OHeroJ** [mdnice/markdown-nice#131]

**Comment by guanpengchn** [comment]
@OHeroJ 请按照规范提问题，否则无法排查

**Comment by OHeroJ** [comment]
给你的个 demo :

## 推荐使用插值的形式来组合字符串和值

如果你之前使用过其他语言，你一定习惯使用大量 + 将字面量字符串以及字符串变量链接构建字符串。 这种方式在 Dart 中同样有效，但是通常情况下使用插值会更清晰简短

```dart
// good
'Hello, $name! You are ${year - birth} years old.';

// bad
'Hello, ' + name + '! You are ' + (year - birth).toString() + ' y...';
```

## 要尽可能的使用集合字面量

```dart
// good
var points = [];
var addresses = {};

// bad
var points = List();
var addresses = Map();
```

## 不要使用 `.length` 来判断一个集合是否为空

通过调用 `.length` 来判断集合是否包含内容是非常低效的。

相反，Dart 提供了更加高效率和易用的 `getter` 函数：`.isEmpty` 和 `.isNotEmpty`。 使用这些函数并不需要对结果再次取非。

```dart
// good
if (lunchBox.isEmpty) return 'so hungry...';
if (words.isNotEmpty) return words.join(' ');

// bad
if (lunchBox.length == 0) return 'so hungry...';
if (!words.isEmpty) return words.join(' ');
```

## 要使用 `whereType()` 按类型过滤集合

假设你有一个 list 里面包含了多种类型的对象， 但是你指向从它里面获取整型类型的数据。 那么你可以像下面这样使用 `where()`:

```dart
// bad
var objects = [1, "a", 2, "b", 3];
var ints = objects.where((e) => e is int);
```

这个很罗嗦，但是更糟糕的是，它返回的可迭代对象类型可能并不是你想要的。 在上面的例子中，虽然你想得到一个 Iterable<int>，然而它返回了一个 Iterable<Object>， 这是因为，这是你过滤后得到的类型。

有时候你会看到通过添加 cast() 来“修正”上面的错误

```dart

// bad
var objects = [1, "a", 2, "b", 3];
var ints = objects.where((e) => e is int).cast<int>();
```

代码冗长，并导致创建了两个包装器，获取元素对象要间接通过两层，并进行两次多余的运行时检查。

```dart

// good
var objects = [1, "a", 2, "b", 3];
var ints = objects.whereType<int>();
```

## 推荐使用 final 关键字来创建只读属性。

如果你有一个变量，对于外部代买来说只能读取不能修改， 最简单的做法就是使用 final 关键字来标记这个变量。

```dart

// good
class Box {
  final contents = [];
}

// bad
class Box {
  var _contents;
  get contents => _contents;
}
```

**Comment by guanpengchn** [comment]
这个可能是highlight.js中dart语言支持导致的问题

**Comment by OHeroJ** [comment]
> 这个可能是highlight.js中dart语言支持导致的问题

之前没问题

**Comment by guanpengchn** [comment]
@OHeroJ 之前是不是代码没有标注dart

**Comment by OHeroJ** [comment]
> @OHeroJ 之前是不是代码没有标注dart

加了

**Comment by guanpengchn** [comment]
@OHeroJ 之前是几月份，哪个版本还有印象么

**Comment by OHeroJ** [comment]
大前天（就是 3 天前）

**Comment by guanpengchn** [comment]
近期未做发布，需要再进行排查

**Comment by guanpengchn** [comment]
已经解决，如果看到新的版本弹出对话框则可
