### ISSUE TITLE
希望能解决脚注不支持空格的问题

### ISSUE THREAD

**Issue by FreddyNietzky** [mdnice/markdown-nice#133]
**新特性描述：**
目前mdnice脚注不支持空格，这样就不能使用英文脚注了。希望改善这个问题，感谢！

**Comment by guanpengchn** [comment]
@FreddyNietzky emmm，让来提issue就是希望把markdown放上来，要不没法复现

**Comment by FreddyNietzky** [comment]
哦抱歉
```
维特根斯坦 (Ludwig Wittgenstein) [云](The sense of ~p *cannot* be understood unless the sense of p has been understood already. "L. Wittgenstein, *Tractus Logico-Philosophicus*")：「我们无法理解一个反题的意义，除非我们已先理解了原命题的意义。」
```
这个时候（脚注内容有空格）无法生成脚注，而脚注的markdown会在本段落显示：
> 维特根斯坦 (Ludwig Wittgenstein) [云](The sense of '~p' cannot be understood unless the sense of 'p' has been understood already. "L. Wittgenstein, _Tractus Logico-Philosophicus_")：「我们无法理解一个反题的意义，除非我们已先理解了原命题的意义。」 

而脚注内容不含空格时
```
维特根斯坦 (Ludwig Wittgenstein) [云](asdfjkl; "L. Wittgenstein, *Tractus Logico-Philosophicus*")：「我们无法理解一个反题的意义，除非我们已先理解了原命题的意义。」
```
可以正常显示：
> 维特根斯坦 (Ludwig Wittgenstein) **云**[6]：「我们无法理解一个反题的意义，除非我们已先理解了原命题的意义。」

并生成备注
> [6]  L. Wittgenstein, _Tractus Logico-Philosophicus_: _asdfjkl;_

**Comment by FreddyNietzky** [comment]
@guanpengchn

**Comment by guanpengchn** [comment]
@FreddyNietzky 好的好的我看看

**Comment by guanpengchn** [comment]
你有木有发现中间的那段文字已经没用了，这个原来就是链接所以会这样的，脚注本身是为了解决微信不支持外链使用的，我建议可以改变个人用法

**Comment by FreddyNietzky** [comment]
@guanpengchn 行8  多谢！

**Comment by guanpengchn** [comment]
不客气的，哈哈
