### ISSUE TITLE
单行公式使用\begin{equation*}标签不正常显示

### ISSUE THREAD

**Issue by ctdhm1984** [mdnice/markdown-nice#135]
**运行环境：**

|操作系统|浏览器|
|---|---|
|win10|Chrome|

**Markdown文本内容：**

例如：

\begin{equation*}
\left.\begin{array}{l}
PA\colon x=my-a\\
MB\colon x=-\frac{a^{2}}{b^{2}m}y+a
\end{array}\right\}\Rightarrow M(\frac{a(b^{2}m^{2}-a^{2})}{a^{2}+b^{2}m^{2}},\frac{2ab^{2}m}{a^{2}+b^{2}m^{2}})
\end{equation*}

**错误详情：**

例如：解析失败

将标签改为$$没有问题

**Comment by views63** [comment]
设定就是这样，不支持 \begin{equation*}，所有环境必须用 定界符 $$ 开始/结束

**Comment by views63** [comment]
另外你的公式本身就有错。正确的应是
```
\begin{equation*}
\left.\begin{array}{l}
PA\colon x=my-a\
MB\colon x=-\frac{a^{2}}{b^{2}m}y+a
\end{array}\right\}\Rightarrow M(\frac{a(b^{2}m^{2}-a^{2})}{a^{2}+b^{2}m^{2}},\frac{2ab^{2}m}{a^{2}+b^{2}m^{2}})
\end{equation*}
```
