### ISSUE TITLE
Linux 下安装后启动报错

### ISSUE THREAD

**Issue by bestsort** [mdnice/markdown-nice#136]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Ubuntu18.04|Chrome|

**错误详情：**
启动报错
`/usr/bin/env: ‘node\r’: No such file or directory`，作者有时间可以做一下 Linux 的支持吗, 查了一下大概是因为开发的时候 Windows 和 Linux 换行符引起的问题

**Comment by guanpengchn** [comment]
@bestsort Linux是支持的，平时在mac下开发，这个肯定没问题的，这个报错的原因是你的node全局变量没有配置好，类似于[这篇文章](https://blog.csdn.net/qq_22716879/article/details/53486819)

**Comment by bestsort** [comment]
> @bestsort Linux 是支持的，平时在 mac 下开发，这个肯定没问题的，这个报错的原因是你的 node 全局变量没有配置好，类似于 [这篇文章](https://blog.csdn.net/qq_22716879/article/details/53486819)

node 有配置， 曾经用过的 `hexo-cli` 和 `ice-work` 都没有问题， 参考上述文章执行命令的时候提示的也是
```bash
ln: failed to create symbolic link '/usr/bin/node': File exists
```

**Comment by guanpengchn** [comment]
这个报错的含义是`/usr/bin/env: ‘node`找不到node指令对吧，你再看看自己的环境情况，我觉得代码本身应该没问题的才对
