### ISSUE TITLE
微信公众号中无法使用行内公式

### ISSUE THREAD

**Issue by hanbaoan123** [mdnice/markdown-nice#137]
**运行环境：**

|操作系统|浏览器|
|---|---|
|window7|360|

**Markdown文本内容：**
$\delta$

**错误详情：**
复制行内公式至微信公众号中会自动换行，如果按退格键会将公式删除。

**Comment by guanpengchn** [comment]
建议在mdnice中排版好，不要在公众号中修改，公式也确实无法修改

**Comment by hanbaoan123** [comment]
> 建议在mdnice中排版好，不要在公众号中修改，公式也确实无法修改

意思是在mdnice中把所有内容输进入？

**Comment by guanpengchn** [comment]
对的，在mdnice中就排版好
