### ISSUE TITLE
链接引用的对应链接为undefined

### ISSUE THREAD

**Issue by LengSword** [mdnice/markdown-nice#144]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows 10|Firefox|

**Markdown文本内容：**

例如：

```md
[以下图片来源][1]

[1]: https://stackoverflow.com/a/31331389	"文中5张图片的来源"
```

**错误详情：**

预览结果的对应链接为undefined.
![图片](https://user-images.githubusercontent.com/24492801/74088844-a41bdb80-4ad5-11ea-8125-29bb26080df0.png)

**Comment by guanpengchn** [comment]
@LengSword 因为兼容性问题，暂时不支持使用该脚注的用法，建议按照文档中的方法使用

**Comment by 88250** [comment]
> @LengSword 因为兼容性问题，暂时不支持使用该脚注的用法，建议按照文档中的方法使用

稍微补充一下：脚注和链接引用是两个不同的概念。链接引用分为引用部分和定义部分，定义部分不渲染；脚注同样也分为引用部分和定义部分，定义部分渲染在文末，并且和引用部分可以通过锚点进行相互页内定位。

**Comment by guanpengchn** [comment]
这个概念解释的很好，哈哈，链接引用因为很少被使用，而且本身就是链接，所以mdnice采取了这种方式生成富文本，用来解决微信不支持外链的问题，本质上还是希望能用链接就用链接，而不是所谓的“脚注”

**Comment by LengSword** [comment]
用脚注代替了, 问题不大
