### ISSUE TITLE
能做一个适配 wordpress 的插件么？有很大一部分 bloger 使用 wordpress.

### ISSUE THREAD

**Issue by martinageradams** [mdnice/markdown-nice#148]
**新特性描述：** 

适配 wordpress 的插件。

1.Wordpress 有群众基础。
2.很多 Wordpress 博客作者关联了公众号。
3.希望有开发者或者作者号召一下，感谢。

**Comment by guanpengchn** [comment]
@w3cfed wordpress我用过，做插件指的是将wordpress的编辑器换掉是吧，这个得等等了，或者看哪位开发者感兴趣

**Comment by mefan** [comment]
有兴趣，关注一下。
