### ISSUE TITLE
目前文章复制到知乎表格还是显示有问题

### ISSUE THREAD

**Issue by jindaxiang** [mdnice/markdown-nice#153]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

例如：

```md
- 默认文本1
- 默认文本2
- 默认文本3
```

**错误详情：**

例如：块级公式转换错误，控制台报错A is undefined

**Comment by guanpengchn** [comment]
知乎不支持表格，所以没办法的
