### ISSUE TITLE
希望增加字数统计的功能

### ISSUE THREAD

**Issue by TopVitamin** [mdnice/markdown-nice#154]
**新特性描述：**

如windows版本的Typora一样，在右下角显示当前输入了多少字数，或者也可以在右侧栏放一个icon，鼠标移动的时候触发显示字数。

字数统计有利于在沉浸式写作的时候，知道自己一共输入了多少内容，当前处于什么状态，对创作者具有一定的标识和指导作用。

**Comment by guanpengchn** [comment]
已经实现
