### ISSUE TITLE
关于公式解析

### ISSUE THREAD

**Issue by xliyq** [mdnice/markdown-nice#157]
我看依赖包中已经有了markdown-it-katex的依赖，目前是否已经支持katex来解析latex公式了？

**Comment by views63** [comment]
不支持

**Comment by xliyq** [comment]
有计划使用katex来解析吗？

**Comment by guanpengchn** [comment]
不会用的，之后会去掉这个包，katex解析公式不如mathjax

**Comment by views63** [comment]
如果后面对性能有更高的要求可以采用 katex 渲染预览窗口，输出的时候换用 mathjax（有少了语法兼容性问题）。
