### ISSUE TITLE
可以增加插入图片调整长宽的特性吗？

### ISSUE THREAD

**Issue by Crayon-ShinChan** [mdnice/markdown-nice#160]
**新特性描述：**
有些小图片可能我们需要插入变小然后居中显示，可以增加方便修改图片大小的特性吗？

具体来说，比如：
1. 插入的图片能等比例缩小到页面宽度的 X%
2. 插入图片非等比例缩放（Optional）

**Comment by guanpengchn** [comment]
已经支持

![image](https://user-images.githubusercontent.com/13995641/79069928-91579a00-7d04-11ea-938e-59f60a82cda3.png)
