### ISSUE TITLE
掘金-代码复制到vscode中变成了一行(格式不正确)

### ISSUE THREAD

**Issue by LinDaiDai** [mdnice/markdown-nice#161]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**问题原因**

上次用发现了新功能-能够复制到掘金上了，很棒棒👍。

但是在使用其排版了掘金文章之后，发现代码片段(主要用的是JavaSscript)，如果复制到其它地方的话(比如vscode)代码的样式就会错乱，变成了一行。
![image](https://user-images.githubusercontent.com/30402039/77153200-53d06a00-6ad4-11ea-8828-32671780e4b3.png)

![image](https://user-images.githubusercontent.com/30402039/77153224-5df26880-6ad4-11ea-83d9-ec2a9d8cf41f.png)

**Comment by guanpengchn** [comment]
指的是发布到掘金之后，再点击复制会出现问题是么

**Comment by guanpengchn** [comment]
文章发下看看

**Comment by LinDaiDai** [comment]
你好👋，是的，在发布到掘金之后，有读者想要复制我的代码，然后发现了这个问题，我去试试的时候也是这样。链接地址： https://juejin.im/post/5e707417e51d45272054d5d3

**Comment by guanpengchn** [comment]
https://juejin.im/post/5e5f0e47f265da57584dad03 忽然发现这篇文章就是正常的

**Comment by guanpengchn** [comment]
已经解决
