### ISSUE TITLE
💖 样式挑战！推荐排版优质的文章和公众号

### ISSUE THREAD

**Issue by guanpengchn** [mdnice/markdown-nice#164]
## 要求

- 欢迎推荐和自荐
- 不是必须使用 mdnice 排版，不是必须微信公众号文章
- 可以推荐多篇文章，但是排版风格不能雷同
- 推荐内容请按照模板来写

希望能够通过这种方式，大家多交流排版技巧，形成自己的排版风格！如果想发推文或者交流文章排版，可以扫码关注后回复[**排版**]，拉入推文群

<img width="400px" src="https://imgkr.cn-bj.ufileos.com/741c4d5c-cfb4-43d9-858b-146661b590df.gif" />

提示：如果总被邮件打扰，请点击 PC 端右下角的 Unsubscribe 取消订阅

## 推荐示例

- 公众号：编程如画
- 推荐文章：[和微信公众号编辑器战斗的日子](https://mp.weixin.qq.com/s/kiTKfif6B2GFZTOd0nM7qw)
- 推荐原因：整体橙色的风格很鲜明，二级标题不错

**Comment by AGJackie** [comment]
三级标题，截图如下：
![](https://imgkr.cn-bj.ufileos.com/d1dc4c1a-d3f5-4277-b01d-e3d989f6f9b8.jpg)
来源推文链接：（我用秀米排的一篇推文）
[爱上精算的一百个理由](https://mp.weixin.qq.com/s/Cm3SVfVbSFzuM7zA-tEFEQ)

**Comment by AGJackie** [comment]
截图链接好像被吞了了。再发一遍
https://imgkr.cn-bj.ufileos.com/d1dc4c1a-d3f5-4277-b01d-e3d989f6f9b8.jpg

**Comment by AGJackie** [comment]
按照要求来写，开个好头哈哈
- 公众号：精算后花园
- 推荐文章：[爱上精算的一百个理由](https://mp.weixin.qq.com/s/Cm3SVfVbSFzuM7zA-tEFEQ)
- 推荐原因：蓝色带箭头的三级标题比较活泼，适合轻阅读的文章
- 三级标题的截图：https://imgkr.cn-bj.ufileos.com/d1dc4c1a-d3f5-4277-b01d-e3d989f6f9b8.jpg

**Comment by CharlieLZ** [comment]
1. 公众号：生财有术
2. 推荐文章：[如何靠一篇软文带来1000+B端客户，创造千万级预估利润？](https://mp.weixin.qq.com/s/v9qaLiQKGFlOoIKKEmCnzA)
3. 推荐原因：排版上，喜欢这种加粗浅颜色覆盖文字的下划线；内容上，软文实操分析方法论和微信情商技巧。
4. 期望模板：用户可自行调整颜色（我更倾向于橙棕色），数字列表作为小标题也随同颜色变化。

**Comment by shenweiyan** [comment]
1. 公众号：BioIT爱好者
2. 推荐文章：[Mdnice 简洁主题](https://mp.weixin.qq.com/s/61OBH4coZDeBHPbbAJekog)
3. 推荐原因：自定义了一二三级的标题，增加了网格的背景风格。
4. 小小建议：现在提交 mdnice 主题，都已经没人审核了吗？好几天过去了，还是一直在"发布审核"中！

**Comment by demo007x** [comment]
公众号：学习派
推荐文章：[正确使用 acme.sh， 让你的网站永久免费使用 ssl 证书](https://mp.weixin.qq.com/s?__biz=Mzg2NjU5MzU4MQ==&mid=2247486713&idx=3&sn=679637c44327144989a1963405d90576&chksm=ce4932bbf93ebbade854f3a063ecee83edaefae90635787423c7b00905c8b6eddc26f01956df&token=1290000562&lang=zh_CN#rd)
推荐原因：自定义了一二三级的标题，增加了网格的背景风格。
图文：[更多图文](https://mp.weixin.qq.com/s?__biz=Mzg2NjU5MzU4MQ==&mid=2247486712&idx=1&sn=5e7178566392cad65760a59ae485a81d&chksm=ce4932baf93ebbaca299473106a78bdca6037010949efcc5650e902d2e89cce4d3f70d0d6251&token=1290000562&lang=zh_CN#rd)
