### ISSUE TITLE
代码在排版的时候没有问题，但是粘贴到掘金，或者公众号时，有的代码间的空格会消失

### ISSUE THREAD

**Issue by yumengh** [mdnice/markdown-nice#170]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

例如：

```md
- 默认文本1
- 默认文本2
- 默认文本3
```

**错误详情：**

例如：块级公式转换错误，控制台报错A is undefined

**Comment by guanpengchn** [comment]
已经修复
