### ISSUE TITLE
右侧不齐平

### ISSUE THREAD

**Issue by dutry** [mdnice/markdown-nice#171]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chromium版edge|

**错误详情：**
排版后截图如下：

![](https://mmbiz.qpic.cn/mmbiz_png/cnJJI9lK9MppmyxueS8KF1clNjagHc5TzHN5Dwgt6onzN037tF8kaT6cmVfmv3vDf76Oj7jrN24Uk9rXDib2mxg/0?wx_fmt=png)

上一段是用mdnice排版的效果，下一段是用微信编辑器排版的效果。可以注意到只有下一段右侧齐平。

**Comment by guanpengchn** [comment]
自定义两端对齐即可

**Comment by dutry** [comment]
解决了……
自定义CSS里添加 text-aligh: justify 即可
