### ISSUE TITLE
到公众号的复制出错

### ISSUE THREAD

**Issue by chenyanzz** [mdnice/markdown-nice#173]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows|QQ浏览器|

**Markdown文本内容：**
似乎任意内容都会这样。

**错误详情：**
复制到微信公众号后台粘贴，只显示一个字母N

好像是时好时坏，有的时候重启一下就好了（？？）

**Comment by guanpengchn** [comment]
推荐使用chrome浏览器，有问题再看看

**Comment by chenyanzz** [comment]
我昨天试了一下，好像是和油猴tanpermonkey的一些插件有冲突，关掉就好了。谢谢。
