### ISSUE TITLE
Safari浏览器下，代码和引用被转换为空

### ISSUE THREAD

**Issue by Sheer-Cold** [mdnice/markdown-nice#178]
浏览器环境：
safari
markdown文本：

`asdada
> Spring Boot makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run".

> We take an opinionated view of the Spring platform and third-party libraries so you can get started with minimum fuss. Most Spring Boot applications need minimal Spring configuration.aaaaa
aaaaaaa
aaaaa

aaaaaa`

粘贴到微信公众号效果：

<img width="644" alt="image" src="https://user-images.githubusercontent.com/20352786/79558614-02b59500-80d7-11ea-9b3b-ca9939adf1c5.png">

**Comment by guanpengchn** [comment]
用chrome吧
