### ISSUE TITLE
掘金代码块越用越小

### ISSUE THREAD

**Issue by yearth** [mdnice/markdown-nice#179]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**代码块使用数量较多的情况**

详情，没使用一次代码块，后面的内容将整体有一定幅度的缩小，最后一个代码块大小几乎只有第一个代码块的 3/4，在移动端效果更明显

[见此文章](https://juejin.im/post/5e9d0ad1e51d4547144282cd)

**Comment by guanpengchn** [comment]
是不是主题问题，正常不会这样的

**Comment by guanpengchn** [comment]
https://juejin.im/post/5ea45570f265da47eb05b8ef 可以看下我的这篇文章

**Comment by guanpengchn** [comment]
目前不支持掘金了
