### ISSUE TITLE
自定义样式无法隐藏 table 的上边框？

### ISSUE THREAD

**Issue by LiarrDev** [mdnice/markdown-nice#181]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Opera|

**Markdown文本内容：**

例如：

```md
<table>
  <tr>
    <td>Hello</td>
    <td>World</td>
  </tr>
</table>
```

**错误详情：**

我自定义了 table 的样式，想让它无边框，但是它还是会有一条上边框：

![截屏2020-04-25 23 58 51](https://user-images.githubusercontent.com/40908569/80284445-1dc87a80-8751-11ea-81ae-e1ee62f9273c.png)

**Comment by guanpengchn** [comment]
#nice table tr {
 border:none
}
