### ISSUE TITLE
极客黑主题二级标题显示问题

### ISSUE THREAD

**Issue by callmexss** [mdnice/markdown-nice#182]
**运行环境：**

|操作系统|浏览器|
|---|---|
|win 10|Chrome|

**Markdown文本内容：**

```md
## 建议5：通过适当添加空行使代码布局更为优雅、合理
```

**错误详情：**

二级标题显示不全，也无法自动换行

![image](https://user-images.githubusercontent.com/29946780/80470572-ca367680-8974-11ea-85dc-66a8ca951c05.png)

**Comment by guanpengchn** [comment]
这个主题对于字数过多进行了隐藏

**Comment by callmexss** [comment]
> 这个主题对于字数过多进行了隐藏

所以这是一个 feature 而不是一个 bug 是吗😂发现自己在大佬的算法群里😂

**Comment by guanpengchn** [comment]
哈哈，是嘛，这个的话确实很多主题没有建立测试case，有很多边界会有问题，这个后续改进吧，暂时建议字数不要太多

**Comment by callmexss** [comment]
好的，谢啦
