### ISSUE TITLE
新版不支持七牛云图床了吗？

### ISSUE THREAD

**Issue by csgajcr** [mdnice/markdown-nice#184]
**新特性描述：**
我看到官方文档中描述的可以支持七牛云、阿里云和自定义图床。
但是我折腾了好一会儿，也没找到七牛云的图床配置要设置在哪。选项里只有图壳图床。

![image](https://user-images.githubusercontent.com/7511628/81033966-15e2a600-8ec8-11ea-82e0-e08ad8962788.png)

**Comment by guanpengchn** [comment]
不支持了

**Comment by csgajcr** [comment]
> 不支持了

希望作者继续支持其他图床（七牛云、腾讯云、阿里云），我使用 mdnice 做个人博客的写作，里面的图片是自己维护，所以希望把图片存到自己的对象存储中。不知道有没有和我一样的小伙伴.... @guanpengchn

**Comment by guanpengchn** [comment]
@csgajcr 会考虑开放出来，还会考虑其他解决方案

**Comment by guanpengchn** [comment]
确定不支持七牛云了，其他的会支持，七牛云并不好用
