### ISSUE TITLE
可支持设置markdown最外层容器的宽度（默认100%）

### ISSUE THREAD

**Issue by Popxie** [mdnice/markdown-nice#186]
**新特性描述：**
> 需求背景：发现这个markdown很好看逼格也很高，于是就想用这个生成的markdown，发邮件使用。但是呢 遇到一个问题就是它默认是铺满整个容器 手机端看还好 没什么难受，但是电脑端查看的时候就会显示的很臃肿 横向留白太多了。  
- 问题和最终效果如下。虽然自己修改源码能达到自己的目的，但是还是希望up主能够支持这个功能，这样我就可以不用盗你的项目发布到我自己的github page了 😂  

![01.png](http://upload-images.jianshu.io/upload_images/12297114-adcf09610aed9766.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![02.png](http://upload-images.jianshu.io/upload_images/12297114-e6396542678410ac.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![3.png](http://upload-images.jianshu.io/upload_images/12297114-c1fbc1d99440d842.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by guanpengchn** [comment]
想发邮件用是么，这波操作可以

**Comment by Popxie** [comment]
> 想发邮件用是么，这波操作可以

哈哈哈 点击复制到掘金以后 直接在邮箱里粘贴 就可以渲染成markdown了 很方便， 但是在复制的时候你设置的样式默认100%。所以放到邮箱里不好看，希望你能增加一个选项设置最外层容器的宽度~ 这样可扩展性高一些，虽然markdown默认都是屏幕有多宽他就有多宽，但是支持自定义宽度且水平居中岂不更好？up主可否考虑下这个优化呢？

**Comment by guanpengchn** [comment]
你有尝试过自定义主题么？我怎么觉得可以解决这个问题呢，并没有你想的这么复杂

**Comment by Popxie** [comment]
> 你有尝试过自定义主题么？我怎么觉得可以解决这个问题呢，并没有你想的这么复杂

没有··· 因为还没有用到那里·· 目前就这个宽度问题，本来打算研究下的 但是手里有工作需求 没时间弄了 就放下了，空了再研究学习下。另外 大佬微信号是机器人嘛？都不回信息··· = =

**Comment by guanpengchn** [comment]
消息太多有时候回复不及时，抱歉
