### ISSUE TITLE
公式不换行

### ISSUE THREAD

**Issue by pluveto** [mdnice/markdown-nice#187]
**Markdown文本内容：**

```md
$$
  I_{D_1}+I_{D_2} = \\
  \int_{0}^{2} \mathrm{d} y \int_{\frac{1}{2} y}^{y} f(x, y) \mathrm{d} x \\
  +\int_{2}^{4} \mathrm{d} y \int_{\frac{1}{2} y}^{2} f(x, y) \mathrm{d} x
$$
```

**错误详情：**

渲染结果没有换行

**Comment by guanpengchn** [comment]
用法不对，前后加

```
$$
\begin{aligned}
  I_{D_1}+I_{D_2} = \\
  \int_{0}^{2} \mathrm{d} y \int_{\frac{1}{2} y}^{y} f(x, y) \mathrm{d} x \\
  +\int_{2}^{4} \mathrm{d} y \int_{\frac{1}{2} y}^{2} f(x, y) \mathrm{d} x
\end{aligned}
$$
```

**Comment by pluveto** [comment]
> 用法不对，前后加
> 
> ```
> $$
> \begin{aligned}
>   I_{D_1}+I_{D_2} = \\
>   \int_{0}^{2} \mathrm{d} y \int_{\frac{1}{2} y}^{y} f(x, y) \mathrm{d} x \\
>   +\int_{2}^{4} \mathrm{d} y \int_{\frac{1}{2} y}^{2} f(x, y) \mathrm{d} x
> \end{aligned}
> $$
> ```

那我从 Typora 编辑完还得全部这么改……

**Comment by guanpengchn** [comment]
typora不支持我的这种写法吗

**Comment by pluveto** [comment]
> typora不支持我的这种写法吗

要多打那么多字符，还是方便一点好

**Comment by views63** [comment]
> 
> 
> > typora不支持我的这种写法吗
> 
> 要多打那么多字符，还是方便一点好

mathjax 3.x 还没实现这个
