### ISSUE TITLE
Python代码缩进显示不正常

### ISSUE THREAD

**Issue by dengdasam** [mdnice/markdown-nice#188]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows|360极速浏览器Chrome内核|

**Markdown文本内容：**

```Python
def solution():
	  ans = 0
	  a = 1  # 数列第1项
	  b = 2  # 数列第2项
	  while a <= 4000000:
		  if b % 2 == 0:
			    ans += x
		  a, b = b, a + b
	  return str(ans)

if __name__ == "__main__":
    print(solution())
```

**错误详情：**

Python代码，代码缩进，显示不正常，复制到微信也显示不正常；4个空格，预览看，有的是4个，有的是2个

**Comment by guanpengchn** [comment]
试试chrome浏览器

**Comment by guanpengchn** [comment]
后来也做过代码修复，估计好了已经

**Comment by dengdasam** [comment]
![](https://static01.imgkr.com/temp/06cce52970ab4bd8b4782ff75059da0e.png)
---
![](https://static01.imgkr.com/temp/f38291fe6da140c990cc97edbc5b2611.jpg)
代码缩进还是有问题啊，Chrome浏览器也一样

**Comment by dengdasam** [comment]
https://static01.imgkr.com/temp/f38291fe6da140c990cc97edbc5b2611.jpg

**Comment by guanpengchn** [comment]
我看现在是没问题，有一些是不是实际上还是两个空格，是敲代码的时候没有统一
