### ISSUE TITLE
本地使用SitDown默认引擎，无法解析不在下拉菜单里的网页内容

### ISSUE THREAD

**Issue by shog86** [mdnice/markdown-nice#189]
**运行环境：**

|操作系统|浏览器|
|macOS|Chrome|

网页：https://www.smartcat.ai/blog/localizing-big-agile-software-kaspersky-case-study/

**错误详情：**

复制网页源文件内容后点 转换， 显示 源代码与已选平台的文章域名不符

**Comment by guanpengchn** [comment]
选其他，引擎没选对
