### ISSUE TITLE
Chrome缓存清理后历史记录丢失

### ISSUE THREAD

**Issue by shiluoheroking** [mdnice/markdown-nice#203]
清理Chrome缓存后，历史记录丢失，怎么找回？

**Comment by shiluoheroking** [comment]
另外上传照片显示失败，重试也不行，啥问题？
![image](https://user-images.githubusercontent.com/53333513/86117547-d28c6880-bb01-11ea-81fe-296153850ec4.png)

**Comment by guanpengchn** [comment]
无法找回，这个现在就是存在本地的，照片问题今天修复了

**Comment by shiluoheroking** [comment]
建议编辑内容持久化到本地指定位置，而不依赖于浏览器缓存，从而避免类似情况发生。

**Comment by guanpengchn** [comment]
好的好的，之后会做的

**Comment by guanpengchn** [comment]
已经做了云存储，未来会存储到本地
