### ISSUE TITLE
掘金IM单行代码样式异常

### ISSUE THREAD

**Issue by zjcscut** [mdnice/markdown-nice#207]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows10|Chrome|

**Markdown文本内容：**

例如：

```md
`SpringBoot`
`单行代码XXXXXXXXXXXXXXXXXXXXXXXXXX`
```

**错误详情：**

例如：CSS有点异常，转换后单行代码块会在右方出现上下箭头按钮，目前发现了主题全栈蓝 + 代码主题atom-one-light（Mac风格）会出现这种情况

![bug](https://user-images.githubusercontent.com/13879735/86600439-a4f86100-bfd2-11ea-8a89-d223a4bbdaa4.png)

**Comment by zjcscut** [comment]
把行内代码中的display: inline-block去掉就好了

**Comment by guanpengchn** [comment]
@zjcscut 我看下，之后调整下

**Comment by zjcscut** [comment]
@guanpengchn 好的大佬

**Comment by guanpengchn** [comment]
掘金暂时不做支持了
