### ISSUE TITLE
想要替换Hexo的默认渲染引擎

### ISSUE THREAD

**Issue by telami** [mdnice/markdown-nice#208]
**新特性描述：**

hexo是一个静态博客，想要直接替换掉hexo的默认markdown渲染，让文章可以直接显示成咱们的页面效果，不知能否给一些思路

**Comment by guanpengchn** [comment]
hexo默认用marked解析器渲染，这个没必要改，mdnice为了适配微信做了很多自己的插件，这些改起来工作太大，建议参考mdnice主题中的css，就足够了

**Comment by telami** [comment]
@guanpengchn 感谢回复，我去试试
