### ISSUE TITLE
(为VSCode 开发markdown-nice插件)Develop plugin of markdown-nice for VSCode

### ISSUE THREAD

**Issue by YuaXan** [mdnice/markdown-nice#217]
**新特性描述：** 
## 为什么开发VSCode 插件
现在VSCode 如日中天的存在，而且VSCode有大批开发者使用。如果需要开发VSCode插件我也可以帮忙

**Comment by guanpengchn** [comment]
暂时还没有精力来做，老哥有什么想法么
