### ISSUE TITLE
sitdown 功能

### ISSUE THREAD

**Issue by liyongning** [mdnice/markdown-nice#218]
sitdown 功能有问题，无法将掘金文章的网页源码转换为markdown文本，提示所选文章的域名与引擎不匹配，没有这个功能使用时候就会很有顾虑的，因为发布后的文章都变成了html，如果我要编辑修改东西，这时候没有原文，则没办法修改；除非自己保存一份原版的markdown文档，但是这样就太麻烦了

**Comment by guanpengchn** [comment]
粘贴过来之后，底部状态栏可以直接转换
