### ISSUE TITLE
Markdown-nice 文档网站不打开

### ISSUE THREAD

**Issue by myerandme** [mdnice/markdown-nice#219]
文档站 https://docs.mdnice.com 使用safai 浏览器和 chrome 都打不开。用了小飞机也不行。不知是 github pages 有问题还是啥问题。

**Comment by guanpengchn** [comment]
那个网站关了，到这里看 https://preview.mdnice.com/articles

**Comment by myerandme** [comment]
> 那个网站关了，到这里看https://preview.mdnice.com/articles
好的，谢谢！
