### ISSUE TITLE
mdnice 图片上传 选择码云图床 上传失败

### ISSUE THREAD

**Issue by lltx** [mdnice/markdown-nice#220]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

![image](https://user-images.githubusercontent.com/50090230/91158043-ad2e6c00-e6f8-11ea-949a-f472326f3995.png)

**错误详情：**

如上图 提示文件名重复问题

**Comment by lltx** [comment]
![image](https://user-images.githubusercontent.com/50090230/91159241-5de93b00-e6fa-11ea-88c1-dbdb722af3bc.png)


每次截图 直接过来文件名 都为 image.png 所以导致 码云失败..

**Comment by guanpengchn** [comment]
哦哦，还有这种问题

**Comment by lltx** [comment]
> 哦哦，还有这种问题

嗯嗯   图片超过 1M 也有坑

https://gitee.com/pig4cloud/oss/raw/master/2020-8-25/wx_camera_1597312389599.jpg

[](https://gitee.com/pig4cloud/oss/raw/master/2020-8-25/wx_camera_1597312389599.jpg)

**Comment by guanpengchn** [comment]
已经解决

**Comment by lltx** [comment]
> 已经解决

牛皮 ， 针对 1M 问题 可以用 imagemin 插件内置压缩一下
