### ISSUE TITLE
屏蔽浏览器Ctrl+S快捷键

### ISSUE THREAD

**Issue by hxz1998** [mdnice/markdown-nice#221]
如果可以而且不麻烦的话，能屏蔽掉浏览器 `Ctrl + S` 的把网页保存下来的功能真是太棒了（随手按 `Ctrl + S` 保存已成习惯 😭）

**Comment by guanpengchn** [comment]
哈哈，自动会保存的呀

**Comment by hxz1998** [comment]
我得改下自己的强迫症了😆
