### ISSUE TITLE
大佬们，请问有安装教程么？

### ISSUE THREAD

**Issue by mucstudio** [mdnice/markdown-nice#223]
大佬们，请问有安装教程么？

想在自己服务器架设一个，但是一直失败。

**Comment by guanpengchn** [comment]
https://preview.mdnice.com/articles

**Comment by haodedong** [comment]
> https://preview.mdnice.com/articles

大佬，网站打不开啦

**Comment by guanpengchn** [comment]
https://product.mdnice.com/articles

**Comment by Theotimus** [comment]
You can use vercel.com import this repo, about couple mins later, you will got one.

And Netlify, Build command: `cl= npm run build` ; Publish directory: `build`
