### ISSUE TITLE
mac 主题丢失 bug

### ISSUE THREAD

**Issue by xgqfrms** [mdnice/markdown-nice#237]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|
|v10.15.7|Version 88.0.4307.2 (Official Build) canary (x86_64)|

**Markdown文本内容：**

```js

// FileName: HelloWorld.js
const log = console.log;

// 向控制台打印一条语句
log("Hello,World!");

class HelloWorld {
  constructor(...args) {
    // 向控制台打印一条语句
    console.log("arguments =", ...args);
  }
}

const hello = new HelloWorld(1, 2, 3);


```

**错误详情：**

> mac 主题丢失 bug

![image](https://user-images.githubusercontent.com/7291672/99762174-d95c5c00-2b32-11eb-82e3-3d36c0e5fa62.png)

![image](https://user-images.githubusercontent.com/7291672/99762341-3eb04d00-2b33-11eb-8f12-01bfeb33e19a.png)

**Comment by guanpengchn** [comment]
会一直丢失么，还是偶尔

**Comment by somenzz** [comment]
我这也是，复制到公众号上代码块上的三个mac图片缺失

**Comment by Cosen95** [comment]
> 我这也是，复制到公众号上代码块上的三个mac图片缺失

有时候应该是网络问题，可以尝试图片重新上传
