### ISSUE TITLE
公式中“-”号有时显示有时候不显示，但是拷贝到微信公众号正常

### ISSUE THREAD

**Issue by kissunyeason** [mdnice/markdown-nice#243]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows|Chrome|

**Markdown文本内容：**

例如：

```md
$$
  \begin{align*}
  (\frac12+\frac{7}{12}-\frac29)÷\frac{1}{36}\\
  \end{align*}
  $$
>$$
  \begin{align*}
  &(\frac12+\frac{7}{12}-\frac{2}{9})÷\frac{1}{36}\\
  =&(\frac12+\frac{7}{12}-\frac{2}{9})×36\\
  =&\frac12×36+\frac{7}{12}×36-\frac{2}{9}×36\\
  =&18+21-8\\
  =&31
  \end{align*}
  $$
```

**错误详情：**
公式中“-”号有时显示有时候不显示，但是拷贝到微信公众号正常
如图
[![DdDNNQ.png](https://s3.ax1x.com/2020/11/25/DdDNNQ.png)](https://imgchr.com/i/DdDNNQ)

**Comment by guanpengchn** [comment]
浏览器放大即可看到


https://user-images.githubusercontent.com/13995641/104404934-c7c58c80-5596-11eb-9156-1f2e4c5d5697.mov
