### ISSUE TITLE
右侧没有复制到掘金的按钮

### ISSUE THREAD

**Issue by MooozzZ** [mdnice/markdown-nice#244]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Comment by hhm-lxb** [comment]
同问，macOs系统么有稀土掘金的复制选项

**Comment by Cosen95** [comment]
> 同问，macOs系统么有稀土掘金的复制选项
目前最新版本已取消对掘金的支持，望周知

**Comment by Cosen95** [comment]
> 同问，macOs系统么有稀土掘金的复制选项

目前最新版本已取消对掘金的支持，望周知

**Comment by hhm-lxb** [comment]
> > 同问，macOs系统么有稀土掘金的复制选项
> 
> 目前最新版本已取消对掘金的支持，望周知

好的
