### ISSUE TITLE
https://www.mdnice.com 白屏

### ISSUE THREAD

**Issue by mynane** [mdnice/markdown-nice#250]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

[https://www.mdnice.com](https://www.mdnice.com)白屏

![image](https://user-images.githubusercontent.com/9946926/104422723-18011680-55b8-11eb-96c4-5ef14134d592.png)
有接口报错

控制台
![image](https://user-images.githubusercontent.com/9946926/104422781-2b13e680-55b8-11eb-98f3-3ed3bdaae071.png)

**Comment by guanpengchn** [comment]
网络请求出错，是网络不通么？

**Comment by Delen0828** [comment]
win10下使用chrome和edge遇到了同样的问题，刷新后会闪现一下页面，然后显示右上角登陆或者是白屏

**Comment by guanpengchn** [comment]
@Delen0828 一直显示不出来么

**Comment by Delen0828** [comment]
> @Delen0828 一直显示不出来么

换用ubuntu下使用chrome和firefox都可以打开，很奇怪
