### ISSUE TITLE
写的文档数据丢失

### ISSUE THREAD

**Issue by tukeyone** [mdnice/markdown-nice#251]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS BigSur 11.0.1|Chrome 87.0.4280.88（正式版本） (x86_64)|

**我写的文档数据丢失：**

**错误详情：**

文档数只有原来的一半了，其他的莫名其妙不见了，麻烦您看下是什么问题了，我的qq：3344382514

**Comment by guanpengchn** [comment]
功能->本地文档，还有提供下注册邮箱，可以看一下数据

**Comment by tukeyone** [comment]
谢谢，已经恢复正常了！

**Comment by tukeyone** [comment]
粘贴过来的图片不显示了
https://imgkr2.cn-bj.ufileos.com/350cdb29-0ac4-4038-9565-386073525f56.png?UCloudPublicKey=TOKEN_8d8b72be-579a-4e83-bfd0-5f6ce1546f13&Signature=5s3LwPKqPcfU8KGp5BbwNCMKN7M%253D&Expires=1611499421
