### ISSUE TITLE
上传图片部分情况下为临时链接一段时间后失效

### ISSUE THREAD

**Issue by DSXiangLi** [mdnice/markdown-nice#253]
用ctrl+V上传图片后，如果链接为 *imgkr2.cn-bj.ufileos.com*， 这个图片会在一段时间后失效。如果链接为*static01.imgkr.com*则有效。可以不稳定复现这个问题，同一个图片上传多次有时会有这个问题，求修复

**Comment by guanpengchn** [comment]
这个是第三方图床的问题，暂时没有解决方案，如果之后条件允许会给长期图片存储

**Comment by guanpengchn** [comment]
已经提供长期存储
