### ISSUE TITLE
上传图片提示 Error: Network Error

### ISSUE THREAD

**Issue by tenngoxars** [mdnice/markdown-nice#260]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Edge|

**错误详情：**

例如：上传图片提示 Error: Network Error

**Comment by guanpengchn** [comment]
chrome试试呢，使用什么图床

**Comment by tenngoxars** [comment]
> chrome试试呢，使用什么图床

是直接粘贴的图片应该是mdnice自带的图床吧？

可能是网络问题，无法准确复现，谢谢回复～
