### ISSUE TITLE
Mdnice的Favicon显示不出来了!!!

### ISSUE THREAD

**Issue by flightmakers** [mdnice/markdown-nice#287]
**运行环境：Chrome 最新版**

Mdnice的Favicon显示不出来了!!!

![Wz7ifH.png](https://z3.ax1x.com/2021/08/01/Wz7ifH.png)]

**Comment by flightmakers** [comment]
@guanpengchn 网站没有图标 导致收藏夹都看不清了

**Comment by guanpengchn** [comment]
现在是不是有了

**Comment by flightmakers** [comment]
哈哈哈
