### ISSUE TITLE
PDF导出不带页眉页脚（可设置为会员服务）

### ISSUE THREAD

**Issue by JasonX2140** [mdnice/markdown-nice#330]
**新特性描述：**
感谢软件，使用了有一年以上，主要是排版公号，部分时候导出PDF。非常好的效率工具。

一个需求是，是否可以设置PDF导出不带页眉页脚等信息，或可自定义页眉页脚信息（非刚需）。可纳入会员服务项目。
![20221015_9NlVYd](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/uPic/20221015_9NlVYd.png!upic)
请问您是否有相关规划？

顺祝商祺。

**Comment by guanpengchn** [comment]
网页端我记得可以设置不导出页眉页脚

**Comment by guanpengchn** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/13995641/196041365-968c6cfd-896a-47f6-8131-3bf145d12078.png">

**Comment by JasonX2140** [comment]
> <img alt="image" width="413" src="https://user-images.githubusercontent.com/13995641/196041365-968c6cfd-896a-47f6-8131-3bf145d12078.png">

谢谢指导，已经解决
