### ISSUE TITLE
样式和PDF功能是否有考虑进入Logseq插件？（可设置为会员服务）

### ISSUE THREAD

**Issue by JasonX2140** [mdnice/markdown-nice#331]
**新特性描述：**
接上一个问题，分开提问。

我是Logseq用户，不知道现在Logseq用户是否比较多，也不知道是否可以插件收费。不知道您是有有考虑开发适配Logseq的插件，这样可以直接复制到公号或导出为PDF。

谢谢

**Comment by guanpengchn** [comment]
这个我是第一次听到的需求，可能暂时不会支持，不好意思

**Comment by JasonX2140** [comment]
收到，感谢回应。不过还是挺期待
