### ISSUE TITLE
window 版本 我购买会员，每天打开时候提示需要激活，激活后还不行，继续提示购买服务，要求退款

### ISSUE THREAD

**Issue by watchpoints** [mdnice/markdown-nice#350]
**运行环境：**

|操作系统|浏览器|
|---|---|
|windowOS|Chrome|

现象：

window 版本 我购买会员，

每天打开时候提示需要激活，激活后还不行，继续提示购买服务，
要求退款。 耐心全部没有了。天天如此。

![image](https://github.com/mdnice/markdown-nice/assets/5937331/41fe5bfa-e79a-419d-bbef-98f0a1f9a793)

![image](https://github.com/mdnice/markdown-nice/assets/5937331/9c83385a-af09-47d4-b8e1-3516ac66aa0b)

![image](https://github.com/mdnice/markdown-nice/assets/5937331/3267efa5-913e-41b8-aa70-fb82e1a73091)

> 最重要第一天登录了，后面第二天继续提示 购买，激活，激活后也是如此。是bug 还是骗人的呢？

**Comment by guanpengchn** [comment]
已经退款处理
