### ISSUE TITLE
数学公式换行问题

### ISSUE THREAD

**Issue by Masir1128** [mdnice/markdown-nice#356]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

例如：

```md
$$\begin{align}
297 =& 2\times9910^2+9\times10 \\ 
=&2\times(99+1)+9\times(9+1)+7\\
=&2\times99+9\times9+2+9+7\\
\end{align}$$
```

**错误详情：**

例如：数学公式换行，标签大小问题，markdown显示没问题，但是在公众号有问题

**Comment by guanpengchn** [comment]
用新版本试试，已经修复了，不行的话用浏览器插件插入也能解决问题
