### ISSUE TITLE
图片存储空间不足，请扩充容量，左下角可查看

### ISSUE THREAD

**Issue by DSXiangLi** [mdnice/markdown-nice#357]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Windows|Chrome|

**Markdown文本内容：**
直接ctrl-V插入图片显示，图片存储空间不足，请扩充容量，左下角可查看。但左下角啥也没有，而且我把之前的几十篇内容都删除后，还是会报相同的错误，想请问下是什么原因

**Comment by guanpengchn** [comment]
editor.mdnice.com

是不是一直在使用旧版，所以看不到

**Comment by DSXiangLi** [comment]
@guanpengchn 点击beta版本会显示无法访问此网站beta.mdnice.com 意外终止了连接。所以一直没有用

**Comment by DSXiangLi** [comment]
@guanpengchn 以及历史图片如何清理呢？我删除了文章似乎没有释放空间

**Comment by guanpengchn** [comment]
网页端可以清理
<img width="358" alt="image" src="https://github.com/mdnice/markdown-nice/assets/13995641/e5d9bc66-decd-42a3-a22a-41b15b8e08c1">

**Comment by guanpengchn** [comment]
访问 https://editor.mdnice.com/ 这个吧，旧版本后期会准备下线
