### ISSUE TITLE
数学公式有问题！

### ISSUE THREAD

**Issue by WGS-note** [mdnice/markdown-nice#358]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

$$
\begin{aligned}
& s_{\tau} = [x_{\tau,1}, \ldots, x_{\tau, L}] \\
& s_{\tau+1} = [x_{\tau+1,1}, \ldots, x_{\tau+1, L}]
\end{aligned} \tag{1}
$$

粘贴到公众号就不行，但是去掉 \tag{} 标签就可以

**Comment by WGS-note** [comment]
\begin{aligned}
& s_{\tau} = [x_{\tau,1}, \ldots, x_{\tau, L}] \\
& s_{\tau+1} = [x_{\tau+1,1}, \ldots, x_{\tau+1, L}]
\end{aligned} \tag{1}

**Comment by guanpengchn** [comment]
试试用浏览器插件来解决

https://product.mdnice.com/membership/vip

**Comment by guanpengchn** [comment]
或者使用\text
