### ISSUE TITLE
能否更换密码？

### ISSUE THREAD

**Issue by Extra-Creativity** [mdnice/markdown-nice#359]
**新特性描述：**

希望可以更换密码，实在没找到更换入口

**Comment by guanpengchn** [comment]
<img width="738" alt="image" src="https://github.com/mdnice/markdown-nice/assets/13995641/d5e27411-76f9-4a6c-a0d6-90b8242bc5cf">

确实没提供更换密码功能，可以先尝试忘记密码更换
