### ISSUE TITLE
“行内公式格式错误，无法进行转换”错误是提示一下公式位置

### ISSUE THREAD

**Issue by YouhuaLi** [mdnice/markdown-nice#37]
**新特性描述：**
我在转化公式时，遇到“行内公式格式错误，无法进行转换”。此时能否在出错信息中提示一下出错公式的位置？比如行号：

第1234行中，发现行内公式格式错误，无法进行转换

否则太难排错了。

感谢。

**Comment by guanpengchn** [comment]
查看下行内公示是否包含空格，会导致出错，这个问题后续会跟进

**Comment by YouhuaLi** [comment]
检查过了，公式里确实没有空格。现在错误变成：Request failed with status code 404

**Comment by guanpengchn** [comment]
能麻烦单独上传一份有问题的markdown文件到GitHub上，或者直接发到我得邮箱，875499765@qq.com

**Comment by guanpengchn** [comment]
@YouhuaLi 也欢迎加入微信群，方便直接沟通，群二维码在README中

**Comment by guanpengchn** [comment]
@YouhuaLi 目前增加了提示，但是只能通过自己核对进行排查，更精确的定位工具后续跟进

**Comment by YouhuaLi** [comment]
感谢，能精确定位就太棒了。

**Comment by guanpengchn** [comment]
@YouhuaLi 
v1.2.2 发布日期：2019-10-11

- 公式编写渲染为svg，彻底解决微信公众号不支持公式的问题
- 组建钉钉用户群
- 解决阿里云图床中文多编码一次的问题

现在已经不会存在上述错误了

**Comment by views63** [comment]
目前的版本如果公式出错会在右边窗口直接显示错误
![图片](https://user-images.githubusercontent.com/175116/66693282-d6f5c480-ecd9-11e9-9d17-8d70234743db.png)

**Comment by guanpengchn** [comment]
@views63 自产自销吧哈哈
