### ISSUE TITLE
多级列表超过三级的内容会消失

### ISSUE THREAD

**Issue by krahets** [mdnice/markdown-nice#39]
- 一级列表
    - 二级列表
        - 三级列表

三级列表内容，在mdnice上预览正常，但复制到公众号平台就消失了，全转到二级列表就没问题了。是我的操作有问题吗？

**Comment by krahets** [comment]
看到文档里描述只能支持到二级标题了，请问是否可以增加支持三级标题的功能？谢谢！

**Comment by guanpengchn** [comment]
@krahets 这件事情还挺有难度的，因为微信不支持，只能放弃ul li标签，改用span来替代，但是要重写markdown解析器，短时间内不会支持，sorry

**Comment by krahets** [comment]
好的，谢谢回复，项目很棒，点赞~

**Comment by guanpengchn** [comment]
@krahets 感谢鼓励，我觉得三级列表可以考虑用标题代替，也许能够暂时解决问题

**Comment by krahets** [comment]
嗯嗯，我现在是把一级列表用六级标题代替了~
