### ISSUE TITLE
工具2.0.0版本开发中，进行主题管理

### ISSUE THREAD

**Issue by guanpengchn** [mdnice/markdown-nice#44]

**Comment by lxfriday** [comment]
code ref [component-based](https://github.com/mdnice/markdown-nice/tree/component-based)

**Comment by lxfriday** [comment]
todo

- [ ] 自动注入 style 文件
- [ ] 提供对外的 props 配置
- [ ] 压缩代码
- [ ] 提供 ts types

**Comment by guanpengchn** [comment]
已完成
