### ISSUE TITLE
希望批量导入照片时能自动排序

### ISSUE THREAD

**Issue by Roy-Kid** [mdnice/markdown-nice#46]
假如我有几十张照片同时上传，在文章中插入的顺序是上传结束的先后顺序。能否自动识别照片文件名以自动排序，或者是在上传结束的列表中提供鼠标拖曳的排序功能？

**Comment by guanpengchn** [comment]
@Roy-Kid 这个问题之前也想过，但是没找到好的解决方案，我再想想

**Comment by Roy-Kid** [comment]
我虽然没做过，我倒是有个思路。就是你摁着ctrl多选文件的时候文件名是按顺序排的，上传的时候先拿到这个顺序，上传完毕往正文插入的时候做个映射行不行？

**Comment by guanpengchn** [comment]
@Roy-Kid 好的好的，我琢磨琢磨，找个合适的解决方案

**Comment by guanpengchn** [comment]
用本地编辑器解决
