### ISSUE TITLE
请问有打算做成npm包的形式吗

### ISSUE THREAD

**Issue by Yaob1990** [mdnice/markdown-nice#48]
**新特性描述：**
做成npm包的形式，继承到其他项目中。
或者给一个说明文档，怎么样集成到博客之类的项目中。
感谢~，真的非常好用。

**Comment by guanpengchn** [comment]
@Yaob1990 有这个计划，下一步要专门做编辑器，目前如果很想用的话，只能用iframe了哈哈

**Comment by guanpengchn** [comment]
@Yaob1990 已经完成，后续继续优化
