### ISSUE TITLE
拖拽上传到阿里云，文件名包含中文会出错

### ISSUE THREAD

**Issue by pdxadp** [mdnice/markdown-nice#53]
**运行环境：**

|操作系统|浏览器|
|Win|Chrome|

**问题描述**

拖拽上传阿里云，文件名包含中文的话，上传成功但返回的图片URL不正确，应该是中文部分被编码了两次导致。

非拖拽上传没问题、不包含中文也没问题。

**Comment by guanpengchn** [comment]
v1.2.2 发布日期：2019-10-11

- 公式编写渲染为svg，彻底解决微信公众号不支持公式的问题
- 组建钉钉用户群
- 解决阿里云图床中文多编码一次的问题

问题已解决
