### ISSUE TITLE
ul ol 粘贴失去 margin-top 和 margin-bottom

### ISSUE THREAD

**Issue by tansongchen** [mdnice/markdown-nice#56]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

例如：

```md
- 巨大边距列表
- 列表
- 列表

1. 另一个列表
2. 列表
3. 列表
```

```css
ol,
ul {
  margin: 3em 2em;
  padding-left: 2em;
}
```

**错误详情：**

![image](https://user-images.githubusercontent.com/31927845/66410492-05586480-e9a7-11e9-9ec9-a62c2c5f80ba.png)

粘贴到微信原生图文编辑器后失去 margin-top 和 bottom（然而，left 和 right 是没有问题的）

![image](https://user-images.githubusercontent.com/31927845/66410665-59634900-e9a7-11e9-9af8-c5c3e5c5a891.png)

另外，我发现 li 不能改颜色的原因是复制到微信后 li 变成了 li p……

**Comment by guanpengchn** [comment]
复制一个li section效果怎么样

**Comment by guanpengchn** [comment]
已经解决
