### ISSUE TITLE
CSS 全局属性的选择器可以使用 article，语义化更好一些

### ISSUE THREAD

**Issue by mytharcher** [mdnice/markdown-nice#58]
**新特性描述：** 如题，`<article>` 是 HTML5 支持的标签，可以用作整个文章的区块元素，同理还可以用 `<footer>`，比 `.layout`/`.footer-*`要更清晰，也更原生。

**Comment by guanpengchn** [comment]
@mytharcher 我印象中最开始也是这么设计的，但是后来发现微信编辑器只支持section，换了其他的div、article、footer这些都不行，你可以实验一下，写一段如下的html代码，然后拷贝到编辑器中，再点击复制

```
<article style="balabala">
balabala
</article>
```

再拷贝到微信编辑器中，很可能行内样式不会生效

**Comment by mytharcher** [comment]
测试了好像的确是这样，感谢解答。
