### ISSUE TITLE
自动图片标注导致连续图片中断

### ISSUE THREAD

**Issue by yuhw2001** [mdnice/markdown-nice#60]
**运行环境：**

在线版，chrome

**Markdown文本内容：**

例如：

```
![img](http://wxdns.xxx.com/mmbiz_png/bYnTNywSLuZQIrtt4G06SLTnRMvQ03RnianJNMq6KvPHOoQibFvhgW9cjTQxRnibjkP6ibibQ16f6qoNLbdocm0h3xQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](http://wxdns.xxx.com/mmbiz_png/bYnTNywSLuZQIrtt4G06SLTnRMvQ03RnibAwZ6nPVAbjPHtbVRM9DnSbxsytl1ZpMbwlAh38NVeyyDFYl3bdkRw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)
```

**错误详情：**
![2019-10-10_155708](https://user-images.githubusercontent.com/19515502/66550093-37202580-eb77-11e9-9d4b-839457ffe8e4.jpg)

转换后连续的图片，因为自动添加图片标注，导致内容中断。
建议对于没有图片标注的内容，不要自动添加。

**Comment by yuhw2001** [comment]
如果markdown中代码没有换行则不出现该问题。
'''
![img](http://wxdns.wedusoft.com/mmbiz_png/bYnTNywSLuZQIrtt4G06SLTnRMvQ03RnK5UGqSKyo3cAtkPLT6Iiby9ibDSwxib83gVF2guJfga7Kxanl9w7HvQIg/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)
![img](http://wxdns.wedusoft.com/mmbiz_png/bYnTNywSLuZQIrtt4G06SLTnRMvQ03RnltOePib1ZW5OzVOCpSOMozWJE0mk7yGXjD6TncgkTEyDO1OH8GxjEGw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)
'''

**Comment by yuhw2001** [comment]
如果markdown中代码没有换行则不出现该问题。
`![img](http://wxdns.wedusoft.com/mmbiz_png/bYnTNywSLuZQIrtt4G06SLTnRMvQ03RnK5UGqSKyo3cAtkPLT6Iiby9ibDSwxib83gVF2guJfga7Kxanl9w7HvQIg/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)
![img](http://wxdns.wedusoft.com/mmbiz_png/bYnTNywSLuZQIrtt4G06SLTnRMvQ03RnltOePib1ZW5OzVOCpSOMozWJE0mk7yGXjD6TncgkTEyDO1OH8GxjEGw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)`

**Comment by guanpengchn** [comment]
@yuhw2001 晚上看下

**Comment by guanpengchn** [comment]
@yuhw2001 这个问题没有复现，这张图片已经打不开了

**Comment by yuhw2001** [comment]
代码如下：
```
![img](https://st2.depositphotos.com/3765753/5349/v/950/depositphotos_53491489-stock-illustration-example-rubber-stamp-vector-over.jpg)

![img](https://www.edrawsoft.com/cn/images/examples/software-service-cross-function-process.png)
```
问题如下：
![2019-10-11_225346](https://user-images.githubusercontent.com/19515502/66661841-4b008000-ec7a-11e9-818b-d2bcbdc57e62.jpg)

**Comment by guanpengchn** [comment]
@yuhw2001 我大概懂你的意思了，可以去掉img这个内容，或者紧挨着，放在一行内，这个在说明文档里有写，`如果是行内图片则无图例，否则有图例`

**Comment by yuhw2001** [comment]
删除图片代码后的"换行"则没问题
![2019-10-11_230004](https://user-images.githubusercontent.com/19515502/66662366-45f00080-ec7b-11e9-9f03-73e66ca9e541.jpg)

**Comment by yuhw2001** [comment]
嗯嗯，测试了一下，懂了“如果是行内图片则无图例，否则有图例”的意思。
不过貌似有没有图例，可能跟换行没多大关系，应该通过代码 [是不是为空] 来标注更合适一些.

![2019-10-11_231513](https://user-images.githubusercontent.com/19515502/66663332-19d57f00-ec7d-11e9-933d-c892f2cda826.jpg)

**Comment by guanpengchn** [comment]
@yuhw2001 这个是解析器的行为，目前相当于有两层吧，第一是是否换行，第二是是否有图例，初看确实觉得有点奇怪，不过我觉得也是合理的
