### ISSUE TITLE
ul和ol渲染时样式被微信编辑器重置的问题

### ISSUE THREAD

**Issue by Daniel-313** [mdnice/markdown-nice#63]
**运行环境：**

|操作系统|浏览器|
|---|---|
| Windows 10 专业版 1903 | Firefox 60.9.0esr (64 位) |

**Markdown文本内容：**

```md
有更好的建议或者意见可以通过以下渠道反馈：

- 小程序内的联系客服；
- 后台回复“内测码”加入Fluency内测群；
- 直接在公众号后台留言；
- QQ群或者微信群直接at群主；
```

**错误详情：**
下图为markdown-nice
![图片](https://user-images.githubusercontent.com/27357588/66621063-57062680-ec15-11e9-9330-8abf38d21632.png)

下图为公众号编辑器
![图片](https://user-images.githubusercontent.com/27357588/66621126-92a0f080-ec15-11e9-8e73-641e6ff5f45c.png)

下图为markdown-nice
![图片](https://user-images.githubusercontent.com/27357588/66620986-14dce500-ec15-11e9-8398-a848dec7e995.png)

下图为公众号编辑器
![图片](https://user-images.githubusercontent.com/27357588/66621000-22926a80-ec15-11e9-8e21-da525fd19787.png)

**Comment by guanpengchn** [comment]
Duplicate of #56

**Comment by guanpengchn** [comment]
已经解决
