### ISSUE TITLE
配色属性和排版样式分开设置

### ISSUE THREAD

**Issue by yuhw2001** [mdnice/markdown-nice#65]
目前样式，如“科技蓝”，既包括颜色又包括排版。
虽然有自定义，但是需要手动修改。
**新特性描述：**
建议，分开两个选项，分别选择配色和排版。
这样，颜色X排版，可以让用户有N多选择，适配自己公众号的格调了。

**Comment by guanpengchn** [comment]
非常好的建议！

**Comment by tansongchen** [comment]
附议！

众所周知，「蓝莹」有 7 个配色😏️

**Comment by guanpengchn** [comment]
#44 提上日程

**Comment by guanpengchn** [comment]
目前暂时不支持，未来会考虑其他方案替代
