### ISSUE TITLE
svg 公式前空格消失、部分行内公式独占一行、少数符号之间排版略紧凑、数量过多时似乎超出了微信容量

### ISSUE THREAD

**Issue by tansongchen** [mdnice/markdown-nice#66]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：** 见附件。

在测试（1）至（3）时，请使用全文的前半段而非全部。

**错误详情：**

（1）正文第一段，「设自由度数为 $n$，」原文中有空格，复制到微信后检查元素无空格；

![image](https://user-images.githubusercontent.com/31927845/66694564-8b0b3700-ec69-11e9-9d0e-77823eabf97b.png)

（2）正文第一组列表，「- Lagrange 形式（$L=T+V$）」原文为（比较短的）行内公式，复制到微信后独占一行（图片同上）；

（3）极少数公式的渲染细节和原生 KaTeX 不完全一致，例如「例如，向前 Euler 算法可以表述为：」后面的那个公式在我的博客上的渲染效果是这样的：

![image](https://user-images.githubusercontent.com/31927845/66694504-0b7d6800-ec69-11e9-9270-2ed24b27bd87.png)

而 Markdown Nice 编辑器内给出的渲染中「等号」和「加号」与其他字符的间距偏小。不过这里不是统一偏小，大部分还是正常的。

![image](https://user-images.githubusercontent.com/31927845/66694586-c0178980-ec69-11e9-8a5b-e2d6cd97d498.png)

（4）将正文全文渲染时，Markdown Nice 复制无问题，但粘贴到微信无响应。（这个应该是微信的问题，没有太大关系，已经很棒啦）

总体来说还是特别感动！爱你们😘️

**Comment by tansongchen** [comment]
原文为：

[symplecticity.txt](https://github.com/mdnice/markdown-nice/files/3720198/symplecticity.txt)

**Comment by views63** [comment]
问题（1）win 上没有重现，可能是 mac 下才有的问题。

问题（2）这个是 li 标签被微信特殊处理了，需要连同 #63 这个一起解决。

问题（3）markdown-nice 现在采用的是 MathJax 跟 KaTeX 有区别是正常的，需要改下写法
```latex
$$
\dot{\mathbf{x}}=C\Rightarrow \mathbf{x(t)}=\mathbf {x_0}+C t
$$
```
问题（4）改用 Firefox 可以改善，或者找个支持 html 模式的公众号插件，直接把复制到的源码黏贴进去也能改善一些。根本问题在于内容太多任何工具都有处理上限。

**Comment by views63** [comment]
问题（1）Mac 下原有的正则表达式  `/\s<svg style/g` 没有匹配到  `<svg xmlns`，已解决。

问题（2）临时的办法：点击复制后，粘贴到文本编辑器内，全局替换 `<li>` 为 `<li><p>`，`</li>` 为 `</p></li>`

问题（3）经测试部分是由于 MathJax 3 的新 bug，Mathjax 2.x 正常（如 `$\mathbf {x}_0+C t$`）。

**Comment by tansongchen** [comment]
经测试 10 月 13 日版上述三个问题已经全部解决。非常感谢！只有很小的细节处理问题：

处理超长块公式时，能否保持字体大小并像代码块一样设为可滚动？（参见 Typora）

```markdown
超长块公式示例：

$$
H=a_1T+b_1V+a_2T+b_2V+...+b_nV+a_{n+1}T
$$
```

处理含下标的行内公式时，下标的一部分会不可见，例如：

```markdown
超高行内公式示例：

时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$，时间 $t_1$
```

![image](https://user-images.githubusercontent.com/31927845/66722272-6675a300-edc0-11e9-922d-978ff7249520.png)

**Comment by tansongchen** [comment]
我试了一下在包围 `svg` 的 `section` 上加 `overflow: scroll`，在编辑器内能使超长公式滚动，但复制到微信后不行。

**Comment by views63** [comment]
> 
> 
> 我试了一下在包围 `svg` 的 `section` 上加 `overflow: scroll`，在编辑器内能使超长公式滚动，但复制到微信后不行。

应该设置 `overflow: auto !important;`

**Comment by tansongchen** [comment]
在 macOS 上，当行内公式出现在标题上时似乎没有将空格替换为 `&nbsp;`。例如：

```markdown
# 格林函数 $G_0$
```

的渲染结果见附件。

[1.txt](https://github.com/mdnice/markdown-nice/files/3746081/1.txt)
