### ISSUE TITLE
markdown diff 功能支持

### ISSUE THREAD

**Issue by lxfriday** [mdnice/markdown-nice#69]
记录下：

**新特性描述：**

下面是掘金、github 的 diff 效果
![image](https://user-images.githubusercontent.com/20264467/66726242-c032a780-ee6a-11e9-8737-d843f889b9e1.png)

内部原理 

![image](https://user-images.githubusercontent.com/20264467/66726296-0ee04180-ee6b-11e9-8072-19132b61e825.png)

如图，当前 markdown diff 代码
![image](https://user-images.githubusercontent.com/20264467/66726222-9c6f6180-ee6a-11e9-81d8-830efd2ce4b6.png)

**Comment by guanpengchn** [comment]
@lxfriday 要不要自己填坑哈哈

**Comment by LinFeng1997** [comment]
当前并没有 markdown 的版本控制，谁和谁 diff 呢？

做一个本地历史功能？然后按一定的时间间隔（比如 5s）把内容存到 indexdb 里。相当于对内容进行了一个快照。

然后用户可以 diff 任意两个快照。

**Comment by LinFeng1997** [comment]
哦 我看错了，你们想要的是代码块的 diff

**Comment by guanpengchn** [comment]
@LinFeng1997 内容回退这个蛮不错的，比如说用户按了ctrl+z可以一直回退那种？哪怕是刷新了浏览器也没问题？

**Comment by LinFeng1997** [comment]
@guanpengchn ctrl+z 可能会和 codemirror 本身的行为冲突，这个可以再讨论。放 indexdb 的话只要它不清浏览器缓存就一直在。

**Comment by guanpengchn** [comment]
@LinFeng1997 这个主意很不错，而且理论上来说不会增加组件包的大小

**Comment by LinFeng1997** [comment]
@guanpengchn 在关于在线编辑 Markdown 这方面，我还有很多主意😀

**Comment by guanpengchn** [comment]
@LinFeng1997 加个微信聊聊？哈哈，aaron875499765

**Comment by lxfriday** [comment]
@LinFeng1997 厉害

**Comment by guanpengchn** [comment]
已经支持
