### ISSUE TITLE
macOS 下 Safari 点复制按钮无效

### ISSUE THREAD

**Issue by views63** [mdnice/markdown-nice#71]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Safari|

点复制无效，选中左侧后点复制无效，右侧随便选中任意字符点击复制才会提示。

**Comment by acccco** [comment]
safari 必须要有选中内容才能复制，不然不会触发 copy 的事件

**Comment by guanpengchn** [comment]
@acccco 要不要帮忙做个fix

**Comment by acccco** [comment]
那你给我，我来改
