### ISSUE TITLE
加粗有Bug

### ISSUE THREAD

**Issue by pdxadp** [mdnice/markdown-nice#72]
如果第一个字符、最后一个字符是标点，加粗就不正常

**Comment by guanpengchn** [comment]
这个是由于commonmark规范所规定的，目前使用的解析器，markdown-it是严格遵守的，所以没有办法，要根据规范来使用，可参考该issue

[Fwd: *emphasis* & **strong** markups not working with symbol chars at the inner closing end ](https://github.com/markdown-it/markdown-it/issues/410)
