### ISSUE TITLE
图片上传增加友好提示

### ISSUE THREAD

**Issue by guanpengchn** [mdnice/markdown-nice#76]
**新特性描述：**

- 拖拽图片到编辑器上方时希望编辑器能有个border高亮
- 对于上传文件类型有提示
- 上传文件大小不应该超过5M，否则微信传不进去

**Comment by lxfriday** [comment]
功能拆分：
- 监听拖拽，加减 border
- 拖拽释放之后，检测文件**大小**和文件**类型**，大小**不能超过 5M**

**Comment by views63** [comment]
gif 帧数也有限制，好像是上限 300 帧

**Comment by guanpengchn** [comment]
@lxfriday 拖拽时最好还要加上当前使用的是哪个图床

**Comment by guanpengchn** [comment]
@views63 gif帧数好像还真没这个数据

**Comment by views63** [comment]
> 
> 
> @views63 gif帧数好像还真没这个数据

试了下，现在只有 gif 5MB的限制了

**Comment by guanpengchn** [comment]
未来图片做压缩解决
