### ISSUE TITLE
通过转换后，复制内容到微信公众号时，提示图片上传失败

### ISSUE THREAD

**Issue by cunyu1943** [mdnice/markdown-nice#80]
**运行环境：**

|操作系统|浏览器|
|---|---|
|windows|Chrome|

**错误详情：**

通过转换后复制到微信时，图片上传失败

**Comment by guanpengchn** [comment]
@cunyu1943 使用的哪个图床，多次粘贴后还会这样么

**Comment by cunyu1943** [comment]
> @cunyu1943 使用的哪个图床，多次粘贴后还会这样么

我用的是github自己的图床，然后多次也会这样

**Comment by guanpengchn** [comment]
@cunyu1943 失败率一定会很高，用阿里云和七牛云的失败率会低，或者用直接提供好的mdnice图床都可以，其他的都很高

**Comment by cunyu1943** [comment]
好的，谢谢

**Comment by edgexie** [comment]
> @cunyu1943 失败率一定会很高，用阿里云和七牛云的失败率会低，或者用直接提供好的mdnice图床都可以，其他的都很高

今天试用了下，mdnice的图床，在知乎上也上传失败。
