### ISSUE TITLE
阿里云图支持

### ISSUE THREAD

**Issue by liaomengge** [mdnice/markdown-nice#84]
一直报如下错误：
RequestError: Failed to fetch (req "error"), PUT https://xxx.oss-cn-beijing.aliyuncs.com/1_20191019220548.png -1 (connected: false, keepalive socket: false) headers: {}

**Comment by liaomengge** [comment]
我看网上是这么说的：https://blog.csdn.net/sechengyan8590/article/details/78554963

**Comment by lxfriday** [comment]
@liaomengge  可以截图控制台打印的错误吗？

**Comment by liaomengge** [comment]
> @liaomengge 可以截图控制台打印的错误吗？

![image](https://user-images.githubusercontent.com/12670328/67157265-7a8b4880-f35c-11e9-8aa6-fdd2252b40bc.png)

**Comment by lxfriday** [comment]
ref to #87 ，先 close 了
