### ISSUE TITLE
代码行号有问题

### ISSUE THREAD

**Issue by lxfriday** [mdnice/markdown-nice#86]
问题发生在**火狐浏览器 69.0.3** ，测试了下

![image](https://user-images.githubusercontent.com/20264467/67147638-22573680-f2c9-11e9-8d75-b783d0d30665.png)

![image](https://user-images.githubusercontent.com/20264467/67147649-3ef36e80-f2c9-11e9-9afc-a4f051a64833.png)

![image](https://user-images.githubusercontent.com/20264467/67147673-7530ee00-f2c9-11e9-9f11-160d54dd0de4.png)

行数是对的，应该是渲染的文字太大，导致**行号**和**代码行**对应不上

在 Chrome 没有出现行号，所以没有这个问题

![image](https://user-images.githubusercontent.com/20264467/67147719-deb0fc80-f2c9-11e9-9180-5788df60302e.png)

**Comment by guanpengchn** [comment]
这个是微信代码的问题，和浏览器应该无关，已经修复了
