### ISSUE TITLE
图片上传错误

### ISSUE THREAD

**Issue by liaomengge** [mdnice/markdown-nice#87]
![image](https://user-images.githubusercontent.com/12670328/67157274-9a227100-f35c-11e9-87f3-f80a8acf1043.png)

![image](https://user-images.githubusercontent.com/12670328/67157281-aeff0480-f35c-11e9-92c0-00e0949bfd3d.png)

**Comment by guanpengchn** [comment]
@liaomengge 方便加下用户群么，好沟通

**Comment by lxfriday** [comment]
@guanpengchn @liaomengge 下一版本加入 sentry，issue 先关掉了
